# Generated by Django 4.1 on 2024-06-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalLink',
        ),
    ]
