# Generated by Django 4.1 on 2024-06-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_educationallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_tasks',
        ),
    ]
