# Generated by Django 4.1 on 2024-06-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_favorite_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
