# Generated by Django 4.1 on 2024-06-25 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_article_sources_commentarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentArticle',
            new_name='ArticleComment',
        ),
    ]
