# Generated by Django 4.1 on 2024-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_articlecomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sources',
            field=models.TextField(blank=True, help_text='Podaj źródła oddzielone przecinkami (,)'),
        ),
    ]
